id: com.gosh.fetch
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
command: gosh-fetch
finish-args:
  - --share=ipc
  - --share=network
  - --socket=fallback-x11
  - --socket=wayland
  - --socket=pulseaudio
  - --device=dri
  - --filesystem=xdg-download:rw
  - --filesystem=xdg-documents:rw
  - --filesystem=xdg-desktop:rw
  - --filesystem=home:rw
  - --filesystem=/media:rw
  - --filesystem=/run/media:rw
  - --filesystem=/tmp:rw
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.kde.StatusNotifierWatcher
  - --talk-name=org.freedesktop.portal.Desktop
modules:
  - name: gosh-fetch
    buildsystem: simple
    build-commands:
      - install -Dm755 gosh-fetch /app/bin/gosh-fetch
      - install -Dm644 512x512.png /app/share/icons/hicolor/512x512/apps/com.gosh.fetch.png
      - install -Dm644 256x256.png /app/share/icons/hicolor/256x256/apps/com.gosh.fetch.png
      - install -Dm644 128x128.png /app/share/icons/hicolor/128x128/apps/com.gosh.fetch.png
      - install -Dm644 com.gosh.fetch.desktop /app/share/applications/com.gosh.fetch.desktop
    sources:
      - type: file
        path: ../../src-tauri/target/release/gosh-fetch
      - type: file
        path: ../../src-tauri/icons/512x512.png
      - type: file
        path: ../../src-tauri/icons/256x256.png
      - type: file
        path: ../../src-tauri/icons/128x128.png
      - type: file
        path: com.gosh.fetch.desktop
